# Generated by Django 4.0.10 on 2023-04-11 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_contactus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='updated_at',
        ),
    ]