# Generated by Django 4.0.10 on 2023-04-12 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_remove_contactus_phone_remove_contactus_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
